# math2d_region.py

import copy

from math2d_polygon import Polygon

class Region(object):
    # These are simply collections of sub-regions.  The sub-regions are assumed
    # to be pair-wise disjoint from one another.  If this requirement is not
    # satisfied, then the result of any method is left undefined.
    def __init__(self):
        self.sub_region_list = []
    
    def Copy(self):
        return copy.deepcopy(self)

    def Tessellate(self):
        for sub_region in self.sub_region_list:
            sub_region.Tessellate()
            
    def ContainsPoint(self, point, epsilon=1e-7):
        for sub_region in self.sub_region_list:
            if sub_region.ContainsPoint(point, epsilon):
                return True
        return False
    
    def CutAgainst(self, other):
        from math2d_planar_graph import PlanarGraph, PlanarGraphEdgeLabel
        graph = PlanarGraph()
        graph.Add(self, False, PlanarGraphEdgeLabel.REGION_BORDER)
        graph.Add(other, False, PlanarGraphEdgeLabel.CUT)
        return graph.ApplyCuts(self)

class SubRegion(object):
    # These are polygons with zero or more holes in them.
    # Each hole is described by a polygon contained within the main polygon of the sub-region.
    # Note that the perimeter and holes of the sub-region are both wound CCW in the plane.
    # If these requirements are not met, then the results of any method are left undefined.
    def __init__(self, polygon=None):
        self.polygon = polygon
        self.hole_list = []
    
    def Copy(self):
        return copy.deepcopy(self)

    def GeneratePolygon(self):
        # Return a polygon covering the same area as this sub-region.
        # If there are holes in this polygon, then the returned polygon
        # will necessarily be self-tangential.
        # TODO: We may want to make use of the planar graph here.  In any case,
        #       What we're trying to do is coalesce all the holes and the perimeter
        #       into one CCW loop.  Any two holes or any hole and the perimeter may
        #       possibly be coalesced into a single hole or an expansion of the perimeter.
        pass

    def Tessellate(self):
        # If you want a triangle mesh for the sub-region, then
        # tessellate the polygon generated by this sub-region.
        self.polygon.Tessellate()
        for hole in self.hole_list:
            hole.Tessellate()
    
    def ContainsPoint(self, point, epsilon=1e-7):
        if not self.polygon.ContainsPoint(point, epsilon):
            return False
        for hole in self.hole_list:
            if hole.ContainsPoint(self, point, epsilon):
                return False
        return True